image: trion/ng-cli-karma

stages:
    - build
    - test
    - lint

cache:
    paths:
        - client/node_modules
        - server/node_modules

lint:
    stage: lint
    script:
        - cd client && npm install && npm run lint
        - cd ..
        - cd server && npm install && npm run lint

build:
    stage: build
    script:
        - cd client && npm install && ng build
        - cd ..
        - cd server && npm install && npm build

test:
    stage: test
    script:
        - cd client && ng test --watch=false --code-coverage --browsers ChromeHeadlessNoSandbox
        - cd ..
        - cd server && npm test
